create type blood_group as enum ('O-','O+','A-','A+','B-','B+','AB-','AB+');
create type request_status as enum ('OPEN','MATCHED','CANCELLED','EXPIRED');
create table donors (id uuid primary key default gen_random_uuid(), user_id uuid unique, name text not null, contact text not null, blood_group blood_group not null, latitude double precision not null, longitude double precision not null, last_donation_date date, availability_status text not null default 'AVAILABLE', notification_consent boolean not null default false, telegram_chat_id text unique, telegram_link_token_hash text unique, telegram_link_token_expires_at timestamptz, notification_paused_until timestamptz, last_notified_at timestamptz, active_match_request_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table blood_requests (id uuid primary key default gen_random_uuid(), requester_id text not null, blood_group blood_group not null, units_required integer not null default 1 check(units_required > 0), hospital text not null, latitude double precision not null, longitude double precision not null, urgency text not null, status request_status not null default 'OPEN', matched_donor_id uuid, created_at timestamptz not null default now());
create table notifications (id uuid primary key default gen_random_uuid(), request_id uuid not null references blood_requests(id), donor_id uuid not null references donors(id), wave_number integer not null, response text not null default 'PENDING', sent_at timestamptz not null default now(), responded_at timestamptz, action_token_hash text not null unique, unique(request_id, donor_id));
create table matches (id uuid primary key default gen_random_uuid(), request_id uuid not null references blood_requests(id), donor_id uuid not null references donors(id), contact_exchange_enabled_at timestamptz, created_at timestamptz not null default now(), unique(request_id, donor_id));
alter table donors enable row level security; alter table blood_requests enable row level security; alter table notifications enable row level security; alter table matches enable row level security;
alter table donors add column if not exists name text;
alter table donors add column if not exists contact text;
alter table donors add column if not exists active_match_request_id uuid;
alter table donors add column if not exists telegram_link_token_hash text unique;
alter table donors add column if not exists telegram_link_token_expires_at timestamptz;
alter table blood_requests add column if not exists matched_donor_id uuid;
