import { NextResponse } from "next/server";
import { acceptNotification, declineNotification } from "@/lib/match-lifecycle";
import { store } from "@/lib/store";
import { answerCallbackQuery, configureTelegramBot, sendTelegramMessage, telegramEntryKeyboard } from "@/lib/telegram";
type TelegramUpdate={message?:{chat:{id:number};text?:string};callback_query?:{id:string;data?:string;message?:{chat:{id:number}}}};
const commands=[{command:"start",description:"Open the BloodLink menu"},{command:"help",description:"Show available actions"},{command:"status",description:"Show your donor status"},{command:"cancel",description:"Learn how to cancel a request"},{command:"disconnect",description:"Disconnect this Telegram chat"}];
const helpText="Use /start to open the menu.\n\nDonate: register or update your donor profile on BloodLink.\nNeed blood: create a request on BloodLink.\n/status: show the status of a chat-linked donor.\n/cancel: request cancellation guidance.\n/disconnect: remove this chat from your donor profile.";
function command(text:string):{name:string;payload?:string}|null{const match=text.trim().match(/^\/([a-z]+)(?:@[a-z0-9_]+)?(?:\s+(.+))?$/i);return match?{name:match[1].toLowerCase(),payload:match[2]?.trim().slice(0,64)}:null;}
function donorStatus(chatId:string):string{const donor=store.donors.find(item=>item.telegramChatId===chatId);if(!donor)return"No donor profile is linked to this Telegram chat yet. Tap “I want to donate” to register on BloodLink.";if(donor.activeMatchRequestId){const request=store.requests.find(item=>item.id===donor.activeMatchRequestId);return request?`Your donor profile is matched to ${request.hospital} for ${request.bloodGroup}. Please follow the blood bank's instructions.`:"Your donor profile has an active match."; }return `Your donor profile is connected and ${donor.availability==="AVAILABLE"?"available for eligible requests":"paused"}.`;}
async function handleMessage(chatId:string,text:string):Promise<void>{const parsed=command(text);if(!parsed){await sendTelegramMessage(chatId,helpText,telegramEntryKeyboard());return;}switch(parsed.name){case"start":await sendTelegramMessage(chatId,parsed.payload?`🩸 Welcome to BloodLink.\n\nYour link code was received (${parsed.payload}). Choose how you want to continue.`:"🩸 Welcome to BloodLink.\n\nChoose how you want to continue.",telegramEntryKeyboard());break;case"help":await sendTelegramMessage(chatId,helpText,telegramEntryKeyboard());break;case"status":await sendTelegramMessage(chatId,donorStatus(chatId));break;case"cancel":await sendTelegramMessage(chatId,"Request cancellation is managed by the requester account in the BloodLink web app. This Telegram chat is not used to guess requester ownership.");break;case"disconnect":{const donor=store.donors.find(item=>item.telegramChatId===chatId);if(donor)donor.telegramChatId=null;await sendTelegramMessage(chatId,donor?"This Telegram chat was disconnected from your donor profile.":"No donor profile was linked to this Telegram chat.");break;}default:await sendTelegramMessage(chatId,helpText,telegramEntryKeyboard());}}
export async function POST(req:Request){const secret=req.headers.get("x-telegram-bot-api-secret-token");if(process.env.MOCK_TELEGRAM!=="true"&&(!process.env.TELEGRAM_WEBHOOK_SECRET||secret!==process.env.TELEGRAM_WEBHOOK_SECRET))return NextResponse.json({error:"Unauthorized webhook"},{status:401});let update:TelegramUpdate;try{update=await req.json() as TelegramUpdate;}catch{return NextResponse.json({error:"Invalid Telegram update"},{status:400});}const callback=update.callback_query;const data=callback?.data;if(data?.startsWith("yes:")||data?.startsWith("accept:")){try{const result=await acceptNotification(data.slice(data.indexOf(":")+1));if(callback)await answerCallbackQuery(callback.id,"Match confirmed. Contact exchange is enabled.");if(callback?.message)await sendTelegramMessage(String(callback.message.chat.id),`🎉 Match confirmed with ${result.request.hospital}. Contact exchange is enabled.`);}catch(error){if(callback)await answerCallbackQuery(callback.id,error instanceof Error?error.message:"Unable to accept");}}else if(data?.startsWith("no:")){try{await declineNotification(data.slice(3));if(callback)await answerCallbackQuery(callback.id,"No problem. You will not be contacted again for this request.");}catch(error){if(callback)await answerCallbackQuery(callback.id,error instanceof Error?error.message:"Unable to decline");}}else if(data==="help"&&callback?.message){await answerCallbackQuery(callback.id,"Here are the available BloodLink actions.");await sendTelegramMessage(String(callback.message.chat.id),helpText,telegramEntryKeyboard());}else if(update.message?.text){try{await configureTelegramBot(commands);await handleMessage(String(update.message.chat.id),update.message.text);}catch(error){console.error(JSON.stringify({event:"telegram_update_failed",error:error instanceof Error?error.message:"unknown"}));return NextResponse.json({error:"Telegram update could not be handled"},{status:502});}}return NextResponse.json({ok:true});}
